# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db5ec052e23e9a5c1b24ab18c2b7d0d819f304d35ef3d022dc5cf0c40a87899f4bcec5123540f4e91b11c114c0636b6fac97583118d811be640fa48a353b616c

test:
  secret_key_base: aa2feca89299b2d8e5583fa53ae3bc7747c799e097a714a9b7c25e7a01d9632ef068ea8ee1e6b129998fc25ca282332d6779e3ca6774e7fe255fa557e536ff43

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: db5ec052e23e9a5c1b24ab18c2b7d0d819f304d35ef3d022dc5cf0c40a87899f4bcec5123540f4e91b11c114c0636b6fac97583118d811be640fa48a353b616c
